"""Generate an OpenFOAM case from a room spec.

This is the only module that knows OpenFOAM's dictionary vocabulary. It takes a
validated :class:`~aicfd.spec.RoomSpec` and writes a complete case directory.

Dictionaries that never vary with the spec (schemes, turbulence and
thermophysical models, gravity) are copied verbatim from ``templates/``.
Everything that depends on the room is generated here, so there is exactly one
place where a modelling choice lives.

The generated case is a build artifact, never edited by hand (ADR-004).
"""

from __future__ import annotations

import math
import shutil
from pathlib import Path

from aicfd.spec import AXES, RHO_AIR, RoomSpec

TEMPLATES = Path(__file__).parent / "templates"

KELVIN = 273.15

#: Darcy-Forchheimer resistance across the rack's blocked axes. Large enough to
#: force air front-to-back as a real rack does, small enough not to wreck the
#: pressure solve.
BLOCKED_D = 1.0e5
BLOCKED_F = 500.0

#: Viscous (Darcy) term on the flow axis. Kept small and fixed: at rack face
#: velocities the drop is dominated by the inertial term, and a non-zero d keeps
#: the source well-behaved as velocity approaches zero.
FLOW_AXIS_D = 20.0

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
  Generated by AICFD from {spec_name}.yaml -- do not edit by hand.
  Regenerate with:  aicfd build {spec_name}
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    {location}object      {obj};
}}
"""


def build(spec: RoomSpec, destination: str | Path) -> Path:
    """Write a complete OpenFOAM case for ``spec`` into ``destination``."""
    case = Path(destination)
    if case.exists():
        shutil.rmtree(case)
    for folder in ("system", "constant", "0"):
        (case / folder).mkdir(parents=True)

    _copy_static(case)
    _write(case / "system/blockMeshDict", _block_mesh_dict(spec))
    _write(case / "system/topoSetDict", _topo_set_dict(spec))
    _write(case / "system/controlDict", _control_dict(spec))
    _write(case / "system/fvSolution", _fv_solution(spec))
    _write(case / "constant/fvOptions", _fv_options(spec))
    for name, text in _initial_fields(spec).items():
        _write(case / "0" / name, text)
    (case / f"{spec.name}.spec.txt").write_text(summary(spec))
    return case


def _copy_static(case: Path) -> None:
    for source in (TEMPLATES / "system").iterdir():
        shutil.copy(source, case / "system" / source.name)
    for source in (TEMPLATES / "constant").iterdir():
        shutil.copy(source, case / "constant" / source.name)


def _write(path: Path, text: str) -> None:
    path.write_text(text if text.endswith("\n") else text + "\n")


def _header(spec: RoomSpec, cls: str, obj: str, location: str | None = None) -> str:
    return HEADER.format(
        spec_name=spec.name,
        cls=cls,
        obj=obj,
        location=f'location    "{location}";\n    ' if location else "",
    )


# --- mesh ---------------------------------------------------------------------


def _block_mesh_dict(spec: RoomSpec) -> str:
    sx, sy, sz = spec.size
    nx, ny, nz = spec.divisions
    return f"""{_header(spec, "dictionary", "blockMeshDict")}
scale   1;

// Room: x 0-{sx:g} (along the airflow), y 0-{sy:g} (across), z 0-{sz:g} (height)
vertices
(
    (0 0 0) ({sx:g} 0 0) ({sx:g} {sy:g} 0) (0 {sy:g} 0)
    (0 0 {sz:g}) ({sx:g} 0 {sz:g}) ({sx:g} {sy:g} {sz:g}) (0 {sy:g} {sz:g})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    fanwall
    {{
        type patch;
        faces ((0 4 7 3));
    }}
    return
    {{
        type patch;
        faces ((1 2 6 5));
    }}
    floor
    {{
        type wall;
        faces ((0 3 2 1));
    }}
    ceiling
    {{
        type wall;
        faces ((4 5 6 7));
    }}
    sidewalls
    {{
        type wall;
        faces ((0 1 5 4) (3 7 6 2));
    }}
);

mergePatchPairs ();
"""


def zone_boxes(spec: RoomSpec) -> dict[str, tuple[tuple[float, ...], tuple[float, ...]]]:
    """The cell-aligned box each rack's zone will actually occupy.

    ``boxToCell`` selects cells whose *centre* falls inside the box, so a box
    edge that lands mid-cell makes the selection depend on floating-point luck.
    Snapping each corner to the nearest cell boundary removes that, and bounds
    the shape error at half a cell per face.

    Rounding to nearest is monotonic, so two disjoint racks can never snap into
    an overlap. They can, however, snap into *contact*: a gap narrower than one
    cell has nowhere to exist on the mesh and closes. That changes the model --
    no air passes between those racks any more -- so it is reported rather than
    left silent.
    """
    boxes = {
        rack.id: (_snap(rack.lo, spec), _snap(rack.hi, spec)) for rack in spec.racks
    }
    racks = {rack.id: rack for rack in spec.racks}
    ids = list(boxes)
    for i, first in enumerate(ids):
        for second in ids[i + 1 :]:
            axis = _closed_gap(racks[first], racks[second], boxes[first], boxes[second])
            if axis is not None:
                spec.warnings.append(
                    f"Racks '{first}' and '{second}' are less than one cell "
                    f"({spec.cell_size_actual[axis]:.3f} m) apart on "
                    f"{AXES[axis]}, so the mesh closes the gap between them and "
                    "they are modelled as one continuous block. Reduce "
                    "mesh.cell_size if the gap matters."
                )
    return boxes


def _closed_gap(rack_a, rack_b, box_a, box_b) -> int | None:
    """The axis whose real gap between two racks vanished on the mesh, if any."""
    for axis in range(3):
        spec_gap = max(rack_a.lo[axis] - rack_b.hi[axis], rack_b.lo[axis] - rack_a.hi[axis])
        if spec_gap <= 0:
            continue  # they are not separated on this axis in the first place
        snapped_gap = max(box_a[0][axis] - box_b[1][axis], box_b[0][axis] - box_a[1][axis])
        if snapped_gap <= 1e-9:
            return axis
    return None


def _topo_set_dict(spec: RoomSpec) -> str:
    boxes = zone_boxes(spec)
    actions = []
    for rack in spec.racks:
        box_lo, box_hi = boxes[rack.id]
        lo = " ".join(f"{v:g}" for v in box_lo)
        hi = " ".join(f"{v:g}" for v in box_hi)
        actions.append(
            f"""    {{
        name    {rack.id};
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ({lo}) ({hi});
    }}
    {{
        name    {rack.id};
        type    cellZoneSet;
        action  new;
        source  setToCellZone;
        set     {rack.id};
    }}"""
        )
    return f"""{_header(spec, "dictionary", "topoSetDict")}
// Rack boxes are snapped to the nearest cell boundary. boxToCell selects by
// cell centre, so an edge landing mid-cell would make the selection depend on
// floating-point rounding.
actions
(
{chr(10).join(actions)}
);
"""


def _snap(point, spec: RoomSpec) -> tuple[float, float, float]:
    """Move a corner to the nearest cell boundary, clamped to the room."""
    cell = spec.cell_size_actual
    return tuple(  # type: ignore[return-value]
        min(max(round(point[axis] / cell[axis]) * cell[axis], 0.0), spec.size[axis])
        for axis in range(3)
    )


# --- physics ------------------------------------------------------------------


def darcy_forchheimer(rack) -> tuple[float, float]:
    """Resistance coefficients along the rack's flow axis.

    The pressure drop through a populated rack at its rated airflow is
    dominated by the inertial (Forchheimer) term, so the whole specified drop is
    assigned there:

        dp = 0.5 * rho * f * u^2 * L   ->   f = 2 * dp / (rho * u^2 * L)

    with ``u`` the face velocity and ``L`` the rack depth. The viscous term
    stays at a small fixed value for numerical robustness.

    Note this makes the rack a *resistance*, not a fan: the air that actually
    passes through it is an outcome of the room's pressure field, not the rated
    airflow. Rack fans as momentum sources are M5.
    """
    velocity = rack.face_velocity_ms
    depth = rack.size[0]
    if velocity <= 0:
        return FLOW_AXIS_D, 0.0
    f = 2.0 * rack.pressure_drop_pa / (RHO_AIR * velocity**2 * depth)
    return FLOW_AXIS_D, f


def _fv_options(spec: RoomSpec) -> str:
    blocks = []
    for rack in spec.racks:
        d_flow, f_flow = darcy_forchheimer(rack)
        blocks.append(
            f"""{rack.id}Porosity
{{
    type            explicitPorositySource;
    active          yes;
    explicitPorositySourceCoeffs
    {{
        selectionMode   cellZone;
        cellZone        {rack.id};
        type            DarcyForchheimer;
        DarcyForchheimerCoeffs
        {{
            // {rack.pressure_drop_pa:g} Pa at {rack.rated_airflow_m3h:,.0f} m3/h
            // ({rack.face_velocity_ms:.2f} m/s through {rack.face_area_m2:.2f} m2)
            d   d [0 -2 0 0 0 0 0] ({d_flow:g} {BLOCKED_D:g} {BLOCKED_D:g});
            f   f [0 -1 0 0 0 0 0] ({f_flow:.4g} {BLOCKED_F:g} {BLOCKED_F:g});
            coordinateSystem
            {{
                type        cartesian;
                origin      (0 0 0);
                coordinateRotation
                {{
                    type    axesRotation;
                    e1      (1 0 0);
                    e2      (0 1 0);
                }}
            }}
        }}
    }}
}}

{rack.id}Heat
{{
    type            scalarSemiImplicitSource;
    active          yes;
    scalarSemiImplicitSourceCoeffs
    {{
        selectionMode   cellZone;
        cellZone        {rack.id};
        volumeMode      absolute;
        injectionRateSuSp
        {{
            // {rack.load_kw:g} kW of IT load.
            // The field is h because thermophysicalProperties uses
            // sensibleEnthalpy; with sensibleInternalEnergy it would be e.
            h           ({rack.load_w:g} 0);
        }}
    }}
}}"""
        )
    return f"""{_header(spec, "dictionary", "fvOptions")}
{chr(10).join(blocks)}
"""


# --- control ------------------------------------------------------------------


def _control_dict(spec: RoomSpec) -> str:
    return f"""{_header(spec, "dictionary", "controlDict")}
application     buoyantSimpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
// An iteration cap, not a target: fvSolution's residualControl should stop the
// run first. Reaching this number means the case did not converge.
endTime         {spec.solver.max_iterations};
deltaT          1;
writeControl    timeStep;
writeInterval   {spec.solver.write_interval};
purgeWrite      2;
writeFormat     ascii;
writePrecision  6;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
"""


def _fv_solution(spec: RoomSpec) -> str:
    tolerance = spec.solver.residual_tolerance
    return f"""{_header(spec, "dictionary", "fvSolution")}
solvers
{{
    "p_rgh.*"
    {{
        solver          GAMG;
        tolerance       1e-8;
        relTol          0.01;
        smoother        GaussSeidel;
    }}
    "(U|h|k|epsilon).*"
    {{
        solver          smoothSolver;
        smoother        GaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }}
}}

SIMPLE
{{
    momentumPredictor yes;
    nNonOrthogonalCorrectors 0;
    consistent      yes;
    residualControl
    {{
        p_rgh           {tolerance:g};
        U               {tolerance:g};
        h               {tolerance:g};
        "(k|epsilon)"   {tolerance:g};
    }}
}}

relaxationFactors
{{
    fields {{ p_rgh 0.7; }}
    equations
    {{
        U               0.3;
        h               0.3;
        "(k|epsilon)"   0.3;
    }}
}}
"""


# --- initial and boundary conditions ------------------------------------------

#: Turbulence intensity for a room-scale recirculating flow. Higher than the
#: 5% used for duct inlets: a data hall is a stirred box, not a clean channel.
TURBULENCE_INTENSITY = 0.10

#: Turbulent length scale as a fraction of room height.
LENGTH_SCALE_FRACTION = 0.1

C_MU = 0.09
T_REFERENCE_K = 293.0


def turbulence_initial_values(spec: RoomSpec) -> tuple[float, float]:
    """Initial k and epsilon for the whole room.

    Two things matter here, and both were got wrong the first time:

    1. **The velocity scale is buoyant, not the supply.** A data hall's supply
       face velocity is slow -- a fifth of a metre per second is normal -- while
       the plume off a rack row runs at ``sqrt(g * dT/T0 * H)``, around 1 m/s.
       Initialising from the supply velocity alone under-estimates k by the
       square of that ratio.

    2. **epsilon must be derived from k, never floored separately.** k and
       epsilon together encode a length scale, ``Cmu^0.75 * k^1.5 / epsilon``.
       Clamping epsilon on its own silently replaces the room-scale length with
       a millimetre one, which collapses the turbulent viscosity to roughly
       molecular. The flow then behaves as if laminar at room scale, and a
       steady solver has no way to settle: it chases vortices that a real,
       turbulent room would damp out. That produced a field with velocities an
       order of magnitude above the buoyant limit.
    """
    buoyant = math.sqrt(
        9.81 * max(min(spec.design_delta_t_k, 30.0), 1.0) / T_REFERENCE_K * spec.size[2]
    )
    characteristic = max(spec.supply_velocity_ms, buoyant)

    k = max(1.5 * (characteristic * TURBULENCE_INTENSITY) ** 2, 1e-6)
    length_scale = LENGTH_SCALE_FRACTION * spec.size[2]
    epsilon = C_MU**0.75 * k**1.5 / length_scale
    return k, epsilon


def _initial_fields(spec: RoomSpec) -> dict[str, str]:
    velocity = spec.supply_velocity_ms
    supply_k = spec.supply_temp_c + KELVIN
    # A plausible return temperature seeds the inletOutlet condition; the solver
    # replaces it as soon as flow leaves the domain.
    return_k = supply_k + min(max(spec.design_delta_t_k, 1.0), 20.0)

    k, epsilon = turbulence_initial_values(spec)

    return {
        "U": f"""{_header(spec, "volVectorField", "U", "0")}
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform ({velocity:.4g} 0 0);

boundaryField
{{
    fanwall
    {{
        // {spec.total_supply_m3s * 3600:,.0f} m3/h over the {spec.supply_patch_area_m2:.2f} m2 wall.
        type            fixedValue;
        value           uniform ({velocity:.4g} 0 0);
    }}
    return     {{ type pressureInletOutletVelocity; value uniform (0 0 0); }}
    floor      {{ type noSlip; }}
    ceiling    {{ type noSlip; }}
    sidewalls  {{ type noSlip; }}
}}
""",
        "T": f"""{_header(spec, "volScalarField", "T", "0")}
dimensions      [0 0 0 1 0 0 0];

internalField   uniform {supply_k:.2f};

boundaryField
{{
    fanwall    {{ type fixedValue; value uniform {supply_k:.2f}; }}
    return     {{ type inletOutlet; inletValue uniform {return_k:.2f}; value uniform {return_k:.2f}; }}
    floor      {{ type zeroGradient; }}
    ceiling    {{ type zeroGradient; }}
    sidewalls  {{ type zeroGradient; }}
}}
""",
        "p_rgh": f"""{_header(spec, "volScalarField", "p_rgh", "0")}
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform 101325;

boundaryField
{{
    fanwall    {{ type fixedFluxPressure; value uniform 101325; }}
    return     {{ type prghPressure; p uniform 101325; value uniform 101325; }}
    floor      {{ type fixedFluxPressure; value uniform 101325; }}
    ceiling    {{ type fixedFluxPressure; value uniform 101325; }}
    sidewalls  {{ type fixedFluxPressure; value uniform 101325; }}
}}
""",
        "p": f"""{_header(spec, "volScalarField", "p", "0")}
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform 101325;

boundaryField
{{
    ".*"       {{ type calculated; value uniform 101325; }}
}}
""",
        "k": f"""{_header(spec, "volScalarField", "k", "0")}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform {k:.4g};

boundaryField
{{
    fanwall    {{ type fixedValue; value uniform {k:.4g}; }}
    return     {{ type inletOutlet; inletValue uniform {k:.4g}; value uniform {k:.4g}; }}
    "(floor|ceiling|sidewalls)" {{ type kqRWallFunction; value uniform {k:.4g}; }}
}}
""",
        "epsilon": f"""{_header(spec, "volScalarField", "epsilon", "0")}
dimensions      [0 2 -3 0 0 0 0];

internalField   uniform {epsilon:.4g};

boundaryField
{{
    fanwall    {{ type fixedValue; value uniform {epsilon:.4g}; }}
    return     {{ type inletOutlet; inletValue uniform {epsilon:.4g}; value uniform {epsilon:.4g}; }}
    "(floor|ceiling|sidewalls)" {{ type epsilonWallFunction; value uniform {epsilon:.4g}; }}
}}
""",
        "nut": f"""{_header(spec, "volScalarField", "nut", "0")}
dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    "(fanwall|return)" {{ type calculated; value uniform 0; }}
    "(floor|ceiling|sidewalls)" {{ type nutkWallFunction; value uniform 0; }}
}}
""",
        "alphat": f"""{_header(spec, "volScalarField", "alphat", "0")}
dimensions      [1 -1 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    "(fanwall|return)" {{ type calculated; value uniform 0; }}
    "(floor|ceiling|sidewalls)" {{ type compressible::alphatWallFunction; Prt 0.85; value uniform 0; }}
}}
""",
    }


# --- human-readable summary ----------------------------------------------------


def summary(spec: RoomSpec) -> str:
    """What the generator derived, in the user's units. Printed by `aicfd build`."""
    lines = [
        f"Case '{spec.name}'",
        f"  Room            {spec.size[0]:g} x {spec.size[1]:g} x {spec.size[2]:g} m",
        f"  Mesh            {'x'.join(str(n) for n in spec.divisions)} "
        f"= {spec.n_cells:,} cells ({spec.cell_size_actual[0]:.3f} m)",
        f"  IT load         {spec.total_load_w / 1000:.1f} kW across "
        f"{len(spec.racks)} rack(s)",
        f"  Supply air      {spec.total_supply_m3s * 3600:,.0f} m3/h at "
        f"{spec.supply_temp_c:.1f} degC",
        f"  Supply velocity {spec.supply_velocity_ms:.3f} m/s "
        f"(over {spec.supply_patch_area_m2:.2f} m2)",
        f"  Design bulk dT  {spec.design_delta_t_k:.1f} K",
        "",
        "  Rack              Load    Rated air   Face vel   DF f",
    ]
    for rack in spec.racks:
        _, f = darcy_forchheimer(rack)
        lines.append(
            f"  {rack.id:<16}{rack.load_kw:>5.1f} kW"
            f"{rack.rated_airflow_m3h:>10,.0f} m3/h"
            f"{rack.face_velocity_ms:>9.2f} m/s"
            f"{f:>8.1f}"
        )
    if spec.warnings:
        lines += ["", "  Warnings:"]
        lines += [f"    - {w}" for w in spec.warnings]
    return "\n".join(lines) + "\n"
