"""Generate an OpenFOAM case for a fan-wall POD.

The M2 generator (:mod:`aicfd.case`) builds a room whose supply and return are
faces of the domain. A POD is not that shape. Its air loop is closed inside one
box -- fan wall, cold aisle, racks, contained hot aisle, ceiling grilles, return
plenum, mechanical gallery -- so every surface that matters is *internal*, and
blockMesh alone cannot express any of it.

So the mesh is built and then operated on:

    blockMesh      one box, six outer walls, nothing else
    topoSet        face zones for each internal surface, cell zones for racks
    createBaffles  turn those face zones into real, two-sided patches
    checkMesh      confirm the surgery left a valid mesh
    buoyantSimpleFoam

Two details cost a lot of time if got wrong, and both are enforced here:

* ``boxToFace`` selects a face whose *centre* falls in the box, whatever its
  orientation. A thin box around a plane therefore also catches every face
  perpendicular to it that happens to pass through. Every face selection is
  narrowed with ``normalToFace``.
* The fan wall is the one place where the loop is cut. It becomes a pair of
  patches on the same internal faces: the gallery side is where air leaves, the
  hall side is where it comes back in at the supply temperature. Which side
  ``createBaffles`` calls master follows the mesh's own face orientation, so it
  is asserted rather than assumed -- see :func:`fan_patch_check`.

The generated case is a build artifact, never edited by hand (ADR-004).
"""

from __future__ import annotations

import math
import shutil
from pathlib import Path

from aicfd.model import BLOCKED_D, BLOCKED_F, Model, Panel, unit_naming

TEMPLATES = Path(__file__).parent / "templates"

KELVIN = 273.15
C_MU = 0.09
T_REFERENCE_K = 293.0

#: Specific gas constant for air, J/(kg K). The pressure the case runs at is
#: the site's, from its altitude (aicfd.model.site_pressure).
R_AIR = 287.05

#: Turbulence intensity for a room-scale recirculating flow (see aicfd.case).
TURBULENCE_INTENSITY = 0.10
LENGTH_SCALE_FRACTION = 0.1

#: The meshing and solving pipeline for a POD. `aicfd.run.solve` takes this.
#:
#: -overwrite is not optional: without it createBaffles writes the baffled mesh
#: into a new time directory and leaves constant/polyMesh untouched, so
#: checkMesh and the solver both read the mesh it was meant to replace -- and
#: neither of them complains.
PIPELINE = (
    "blockMesh",
    "topoSet",
    ("createBaffles", ["-overwrite"]),
    "checkMesh",
    "buoyantSimpleFoam",
)

#: Everything up to the solver, for checking the mesh without paying for a run.
MESH_PIPELINE = PIPELINE[:-1]


def pipeline(processors: int = 1) -> tuple:
    """The pipeline for ``processors`` cores.

    Past one core the solver runs under mpirun on a decomposed mesh, and the
    fields are stitched back together at the end. The sampler reconstructs
    each intermediate write itself (see post.sample), so the run can still
    be watched. Logs keep the solver's name whichever way it is launched.
    """
    if processors <= 1:
        return PIPELINE
    return MESH_PIPELINE + (
        ("decomposePar", ["-force"]),
        ("mpirun", ["-np", str(processors), "buoyantSimpleFoam", "-parallel"],
         "buoyantSimpleFoam"),
        ("reconstructPar", ["-latestTime"]),
    )

#: The outer box. Every one of these is a wall: a POD's air never leaves it.
OUTER_PATCHES = ("galleryBack", "hallEnd", "coldWall", "hotWall", "floor", "slab")

#: Where the loop is cut. Air leaves the gallery here and re-enters the hall at
#: the supply temperature -- which is exactly what the fan wall does.
FAN_INTAKE = "fanIntake"
FAN_SUPPLY = "fanSupply"

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
  Generated by AICFD from {name}.yaml -- do not edit by hand.
  Regenerate with:  aicfd build cases/{name}.yaml
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    {location}object      {obj};
}}
"""


def build(model: Model, destination: str | Path, max_iterations: int = 400,
          residual_tolerance: float = 1.0e-4, sensor_interval: int = 100,
          warm_start_field: bool = True, processors: int = 1) -> Path:
    """Write a complete OpenFOAM case for ``model`` into ``destination``."""
    case = Path(destination)
    if case.exists():
        shutil.rmtree(case)
    for folder in ("system", "constant", "0"):
        (case / folder).mkdir(parents=True)

    for source in (TEMPLATES / "system").iterdir():
        shutil.copy(source, case / "system" / source.name)
    for source in (TEMPLATES / "constant").iterdir():
        shutil.copy(source, case / "constant" / source.name)

    _write(case / "system/blockMeshDict", block_mesh_dict(model))
    _write(case / "system/topoSetDict", topo_set_dict(model))
    _write(case / "system/createBafflesDict", create_baffles_dict(model))
    _write(case / "system/controlDict",
           control_dict(model, max_iterations, sensor_interval))
    _write(case / "system/fvSolution", fv_solution(model, residual_tolerance))
    _write(case / "constant/fvOptions", fv_options(model))
    if processors > 1:
        _write(case / "system/decomposeParDict", decompose_par_dict(model, processors))
    for name, text in initial_fields(model, warm_start_field).items():
        _write(case / "0" / name, text)
    (case / f"{model.name}.model.txt").write_text(summary(model))
    return case


def _write(path: Path, text: str) -> None:
    path.write_text(text if text.endswith("\n") else text + "\n")


def _header(model: Model, cls: str, obj: str, location: str | None = None) -> str:
    return HEADER.format(
        name=model.name,
        cls=cls,
        obj=obj,
        location=f'location    "{location}";\n    ' if location else "",
    )


def supply_density(model: Model) -> float:
    """Air density at the supply temperature, from the ideal gas law.

    The fan is set up by mass flow, and this has to be the density the solver
    itself computes at the supply patch. A nominal 1.19 would leave a percent
    of mass imbalance in a domain that has nowhere to put it.
    """
    return model.pressure_pa / (R_AIR * (model.supply_temp_c + KELVIN))


def _v(point) -> str:
    return " ".join(f"{value:.6g}" for value in point)


# --- mesh ---------------------------------------------------------------------


def block_mesh_dict(model: Model) -> str:
    sx, sy, sz = model.domain.size
    nx, ny, nz = model.divisions
    return f"""{_header(model, "dictionary", "blockMeshDict")}
scale   1;

// x 0-{sx:g}: gallery, then the data hall.  y 0-{sy:g}: cold aisle, rack row,
// hot aisle.  z 0-{sz:g}: floor to slab, with the false ceiling at
// {model.ceiling_z:g} m built later as a baffle.
vertices
(
    (0 0 0) ({sx:g} 0 0) ({sx:g} {sy:g} 0) (0 {sy:g} 0)
    (0 0 {sz:g}) ({sx:g} 0 {sz:g}) ({sx:g} {sy:g} {sz:g}) (0 {sy:g} {sz:g})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

// The POD's air never leaves the box: the loop is closed inside it, and the
// fan wall (an internal baffle pair) is the only place it is cut.
boundary
(
    galleryBack {{ type wall; faces ((0 4 7 3)); }}
    hallEnd     {{ type wall; faces ((1 2 6 5)); }}
    coldWall    {{ type wall; faces ((0 1 5 4)); }}
    hotWall     {{ type wall; faces ((3 7 6 2)); }}
    floor       {{ type wall; faces ((0 3 2 1)); }}
    slab        {{ type wall; faces ((4 5 6 7)); }}
);

mergePatchPairs ();
"""


#: Which panels share one face zone, and so one two-sided patch. A hall has
#: thirty-two rack tops; giving each its own patch would multiply the boundary
#: file for nothing, since they are all the same adiabatic wall. Grouping by
#: what a surface *is* keeps the patch list readable and the leak check (which
#: reports per zone) still says which kind of surface leaks.
WALL_GROUPS = (
    ("rack_top", "rack_top"),
    ("rack_end", "rack_end"),
    # A BLANKING PANEL IS A WALL. It was in the model, on the drawing and in
    # the summary, and it was not in this tuple -- so `createBaffles` never
    # built one and the solver saw an open hole where the plate is. Measured
    # on a hall with one blank in every fifteen positions: 3,83 m3/s came out
    # of that one position at 2,8 m/s, 28% of what the whole row of fourteen
    # cabinets passed, and the row delivered 54% of the resistance its curve
    # asks for (ADR-081).
    ("blank", "blank"),
    # A COLD AISLE IS CLOSED BY A LID, normal to z, so it is a zone of its own
    # -- a zone shares a normal. It was built in the model and absent from
    # this tuple, so `createBaffles` never made it and the solver saw an open
    # cold aisle: the rows delivered 4% of their rated resistance and the
    # warmest intake read 47 degC. The FOURTH time a new panel was modelled
    # and not meshed (ADR-081, ADR-100), and the last: `wall_plan` is now
    # checked against every wall the model builds.
    ("containment_lid", "containment_lid"),
    ("containment_wall", "containment_roofwall"),
    ("containment_wall", "containment_wall"),
    ("containment_door", "containment_door"),
    # THE SIDE OF A CONTAINED COLD AISLE, where a cage wall stands in it. A
    # contained aisle cannot end on a cage wall, so it closes with a side of
    # its own -- and a side that is built and never meshed is a hole, which is
    # the fault this list has been caught by five times (ADR-110).
    ("containment_side", "containment_side"),
)


#: Panels that become one two-sided internal wall each, and the holes punched
#: through them. A hole is another panel: the fan walls and the plenum opening
#: are holes in the dividing wall, the grilles are holes in the false ceiling.
def wall_plan(model: Model) -> list[tuple[str, list[Panel], list[Panel]]]:
    """(zone name, the surfaces in it, the panels that are holes in them)."""
    plan: list[tuple[str, list[Panel], list[Panel]]] = []

    # One dividing wall per mechanical gallery, each pierced by its own units
    # and by its own opening into the (single) return plenum.
    for i, x in enumerate(model.dividers):
        name = "divider" if i == 0 else f"divider{i + 1}"
        divider = Panel(
            name,
            "wall",
            axis=0,
            position=x,
            extent=((0.0, model.domain.hi[1]), (0.0, model.domain.hi[2])),
        )
        holes = [
            p
            for p in model.panels
            if (p.kind == "fan" or p.name.startswith(("plenum_opening",
                                                       "floor_opening")))
            and abs(p.position - x) < 1e-6
        ]
        plan.append((name, [divider], holes))

    # A supply plenum makes that wall a double wall: the second leaf stands a
    # short way into the hall, and it is the one the grilles are in. The units
    # and the wall they are mounted in are untouched (ADR-058).
    for wall in [p for p in model.panels if p.name.startswith("plenum_wall")]:
        plan.append((
            wall.name,
            [wall],
            [p for p in model.panels
             if p.name.startswith("supply") and abs(p.position - wall.position) < 1e-6],
        ))

    grilles = [p for p in model.panels if p.name.startswith("grille")]
    plan.append(("forro", [model.panel("ceiling")], grilles))

    # The raised floor is the false ceiling's twin, the other way up: a wall
    # across the whole footprint, perforated where the air is meant to come
    # through. Its holes are the plates in the cold aisles and, in the
    # gallery, the face each unit discharges through (ADR-076).
    deck = next((p for p in model.panels if p.name == "floor_deck"), None)
    if deck is not None:
        holes = [p for p in model.panels
                 if p.name.startswith("tile_")
                 or (p.kind == "fan" and abs(p.position - deck.position) < 1e-6)]
        plan.append(("piso", [deck], holes))

    # A DRYWALL CAGE IS FOUR WALLS WITH TWO NORMALS -- two across the rows and
    # two along them -- so it cannot be one zone: a zone shares a normal, and
    # `_face_selection` asserts it. One zone per wall, named after the panel,
    # the way each fan wall gets its own. A MESH cage is not here at all: it
    # resists the air, so `porous()` claims it and it becomes a cyclic pair
    # with the jump on it (ADR-096).
    for wall in [p for p in model.panels
                 if p.name.startswith("cage_") and p.resistance is None]:
        plan.append((wall.name, [wall], []))

    for zone in dict.fromkeys(group for group, _prefix in WALL_GROUPS):
        prefixes = tuple(prefix for group, prefix in WALL_GROUPS if group == zone)
        # A panel that RESISTS the air is not a member of a wall zone: it is
        # its own zone, claimed by `porous()`, and a face in two zones is
        # what `createBaffles` refuses. The cage is the surface that made
        # this explicit -- drywall is a wall and mesh is a resistance, under
        # the same name prefix (ADR-096).
        members = [p for p in model.panels
                   if p.name.startswith(prefixes) and p.resistance is None]
        if members:
            plan.append((zone, members, []))
    return plan


def _face_selection(name: str, panels: list[Panel], holes: list[Panel], cell) -> str:
    """topoSet actions that leave ``name`` holding exactly these panels' faces.

    Every panel in a zone shares a normal, so one normalToFace narrows them
    all; the boxes are added one by one before it.
    """
    axis = panels[0].axis
    assert all(p.axis == axis for p in panels), name
    # thin enough that only faces *on* the plane qualify -- a quarter of the
    # cell along the panel's own normal, which is the axis that matters
    half = cell[axis] * 0.25
    eps = 1e-6
    normal = [0, 0, 0]
    normal[axis] = 1

    def box(target: Panel) -> str:
        lo = [0.0, 0.0, 0.0]
        hi = [0.0, 0.0, 0.0]
        lo[axis] = target.position - half
        hi[axis] = target.position + half
        for in_plane, (a0, a1) in zip(target.in_plane_axes, target.extent):
            lo[in_plane], hi[in_plane] = a0 - eps, a1 + eps
        return f"({_v(lo)}) ({_v(hi)})"

    actions = [
        f"""    {{
        name    {name}Faces;
        type    faceSet;
        action  {"new" if i == 0 else "add"};
        source  boxToFace;
        box     {box(panel)};
    }}"""
        for i, panel in enumerate(panels)
    ]
    actions.append(
        f"""    {{
        // boxToFace takes any face whose centre is in the box, including the
        // ones running perpendicular through it. Only faces normal to
        // {"xyz"[axis]} belong to this surface.
        name    {name}Faces;
        type    faceSet;
        action  subset;
        source  normalToFace;
        normal  ({_v(normal)});
        cos     0.01;
    }}"""
    )
    for hole in holes:
        actions.append(
            f"""    {{
        // {hole.name} is a hole in {name}, not a wall.
        name    {name}Faces;
        type    faceSet;
        action  delete;
        source  boxToFace;
        box     {box(hole)};
    }}"""
        )
    actions.append(
        f"""    {{
        name    {name};
        type    faceZoneSet;
        action  new;
        source  setToFaceZone;
        faceSet {name}Faces;
    }}"""
    )
    return "\n".join(actions)


def topo_set_dict(model: Model) -> str:
    cell = model.cell_size
    actions = [
        _face_selection(name, panel, holes, cell)
        for name, panel, holes in wall_plan(model)
    ]
    for fan in model.fans:
        if fan.return_z is None:
            actions.append(_face_selection(fan.name, [fan], [], cell))
            continue
        # A downflow unit is two zones, one per face, because each carries its
        # own condition and they are a storey apart (ADR-076).
        import dataclasses as _dc

        actions.append(_face_selection(f"{fan.name}_supply", [fan], [], cell))
        actions.append(_face_selection(
            f"{fan.name}_return",
            [_dc.replace(fan, position=fan.return_z)], [], cell))
    # Each grille is its own zone: it becomes a cyclic pair carrying the
    # datasheet's pressure loss, not a hole. The forro zone above already has
    # these faces removed, so nothing is claimed twice.
    for surface in porous(model):
        actions.append(_face_selection(surface.name, [surface], [], cell))

    for rack in model.racks:
        actions.append(
            f"""    {{
        name    {rack.id};
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ({_v(rack.box.lo)}) ({_v(rack.box.hi)});
    }}
    {{
        name    {rack.id};
        type    cellZoneSet;
        action  new;
        source  setToCellZone;
        set     {rack.id};
    }}"""
        )
    return f"""{_header(model, "dictionary", "topoSetDict")}
// Every plane here already lands on a cell face: aicfd.model snaps the
// geometry to the mesh before anything reads it (ADR-014).
actions
(
{chr(10).join(actions)}
);
"""


# --- baffles ------------------------------------------------------------------


def _wall_patch_fields(k: float, epsilon: float, p0: float) -> str:
    return f"""            patchFields
            {{
                U       {{ type noSlip; }}
                T       {{ type zeroGradient; }}
                p_rgh   {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
                p       {{ type calculated; value uniform {p0:.0f}; }}
                k       {{ type kqRWallFunction; value uniform {k:.4g}; }}
                epsilon {{ type epsilonWallFunction; value uniform {epsilon:.4g}; }}
                nut     {{ type nutkWallFunction; value uniform 0; }}
                alphat  {{ type compressible::alphatJayatillekeWallFunction;
                          Prt 0.85; value uniform 0; }}
            }}"""


def porous(model: Model) -> list[Panel]:
    """Every surface the air passes THROUGH at a cost, in zone order.

    A ceiling return grille and the woven mesh closing the plenum where it
    opens into a gallery are the same thing to the solver: a hole in a wall
    that is also a pressure jump. Each is a hole in its wall's zone so the
    wall does not block it, and a face zone of its own so the jump has
    somewhere to live (ADR-048).
    """
    return [p for p in model.panels
            if p.resistance is not None
            and p.name.startswith(("grille", "plenum_opening", "supply",
                                   "floor_opening", "tile_", "cage_"))]


def _porous_baffle(grille: Panel, p0: float) -> str:
    """A perforated surface as a cyclic pair with a pressure jump across it.

    porousBafflePressure gives dp = -(D mu U + 0.5 I rho |U|^2) L on the
    pressure the solver works with, here p_rgh. With D = 0 and L = 1 the
    inertial coefficient *is* the loss coefficient K from the datasheet's
    free area, referred to the face velocity through the gross opening --
    exactly what the grille catalogue's dp-vs-velocity table encodes. The
    cyclic base means every other field passes straight through; only the
    pressure sees the grille.
    """
    K = grille.resistance if grille.resistance is not None else 0.0
    below, above = f"{grille.name}_below", f"{grille.name}_above"
    cyclic = "\n".join(
        f"                    {f:<7} {{ type cyclic; }}"
        for f in ("U", "T", "p", "k", "epsilon", "nut", "alphat")
    )

    def side(name: str, other: str) -> str:
        return f"""            {{
                name    {name};
                type    cyclic;
                neighbourPatch  {other};
                patchFields
                {{
{cyclic}
                    p_rgh   {{ type porousBafflePressure; patchType cyclic;
                              D 0; I {K:.4g}; length 1;
                              jump uniform 0; value uniform {p0:.0f}; }}
                }}
            }}"""

    return f"""    {grille.name}
    {{
        // {grille.area:.2f} m2 return grille, K = {K:.3g} on the face velocity
        type        faceZone;
        zoneName    {grille.name};
        patches
        {{
            master
{side(below, above)}
            slave
{side(above, below)}
        }}
    }}"""


def fan_patches(model: Model) -> list[tuple[str, str]]:
    """(intake, supply) patch names for every fan wall, in order.

    A POD's single unit keeps the names ``fanIntake``/``fanSupply``; a hall's
    units are ``fan1Intake``, ``fan2Supply`` and so on, after their panels.
    """
    return [(f"{fan.name}Intake", f"{fan.name}Supply") for fan in model.fans]


def create_baffles_dict(model: Model) -> str:
    k, epsilon = turbulence_initial_values(model)

    p0 = model.pressure_pa
    entries = [_porous_baffle(s, p0) for s in porous(model)]
    for name, _panels, _holes in wall_plan(model):
        entries.append(
            f"""    {name}
    {{
        type        faceZone;
        zoneName    {name};
        patchPairs
        {{
            type    wall;
{_wall_patch_fields(k, epsilon, p0)}
        }}
    }}"""
        )

    for fan in model.fans:
        if fan.return_z is None:
            entries.append(_fan_baffle(model, fan, k, epsilon))
        else:
            entries += _downflow_baffles(model, fan, k, epsilon)

    return f"""{_header(model, "dictionary", "createBafflesDict")}
// Turn internal faces into real two-sided patches. Everything here is inside
// the box, so nothing may touch the outer boundary.
internalFacesOnly true;

baffles
{{
{chr(10).join(entries)}
}}
"""


def _downflow_baffles(model: Model, fan: Panel, k: float,
                      epsilon: float) -> list[str]:
    """A downflow unit as TWO baffles, each with one working side (ADR-076).

    The fan wall is one plane doing both jobs: the air leaves the gallery
    through one side of it and arrives in the hall through the other. A
    downflow unit's two faces are a storey apart, so each plane carries one
    condition and a wall behind it -- the return draws from the gallery above
    it and is a wall underneath, the supply delivers into the plenum below it
    and is a wall on top. Give both sides of both planes a condition and the
    unit runs twice.

    The mass is the same at each: what the top takes out, the bottom puts
    back. Volume would not do -- the air leaving is warmer and thinner than
    the air arriving, and in a loop with nowhere to store the difference a 1%
    mismatch has no way out.
    """
    supply_k = model.supply_temp_c + KELVIN
    p0 = model.pressure_pa
    mass_flow = model.unit_airflow_m3h / 3600.0 * supply_density(model)
    intake, supply = f"{fan.name}Intake", f"{fan.name}Supply"
    wall = _wall_patch_fields(k, epsilon, p0)

    intake_fields = f"""                patchFields
                {{
                    // {model.unit_airflow_m3h:,.0f} m3/h out of the gallery, through the
                    // top of the unit: {mass_flow:.4g} kg/s over {fan.area:.2f} m2.
                    U       {{ type flowRateOutletVelocity;
                              massFlowRate {mass_flow:.6g};
                              rho rho; value uniform (0 0 0); }}
                    // inletOutlet and not zeroGradient, for the same reason
                    // the fan wall's intake is: zeroGradient stores no value
                    // on the patch, and the temperature of the air crossing
                    // here is the number the energy balance is built from.
                    T       {{ type inletOutlet;
                              inletValue uniform {supply_k:.2f};
                              value uniform {supply_k:.2f}; }}
                    p_rgh   {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
                    p       {{ type calculated; value uniform {p0:.0f}; }}
                    k       {{ type zeroGradient; }}
                    epsilon {{ type zeroGradient; }}
                    nut     {{ type calculated; value uniform 0; }}
                    alphat  {{ type calculated; value uniform 0; }}
                }}"""
    supply_fields = f"""                patchFields
                {{
                    // The same {mass_flow:.4g} kg/s back in at {model.supply_temp_c:g} degC,
                    // down through the deck into the underfloor plenum.
                    U       {{ type flowRateInletVelocity;
                              massFlowRate {mass_flow:.6g};
                              rho rho; value uniform (0 0 0); }}
                    T       {{ type fixedValue; value uniform {supply_k:.2f}; }}
                    p_rgh   {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
                    p       {{ type calculated; value uniform {p0:.0f}; }}
                    k       {{ type fixedValue; value uniform {k:.4g}; }}
                    epsilon {{ type fixedValue; value uniform {epsilon:.4g}; }}
                    nut     {{ type calculated; value uniform 0; }}
                    alphat  {{ type calculated; value uniform 0; }}
                }}"""

    def half(role: str, name: str, fields: str, kind: str = "patch") -> str:
        return f"""            {role}
            {{
                name    {name};
                type    {kind};
{fields}
            }}"""

    # createBaffles hands the master patch to the face's owner cell, which for
    # a z-normal face of a blockMesh box is the cell BELOW it. Under the
    # supply face that is the plenum, so the supply is the master; under the
    # return face it is the unit's own body, and the gallery it draws from is
    # above, so there the intake is the slave.
    # A UNIT OUT OF SERVICE IS A BOX. Both faces are walls -- it moves no
    # air and cools nothing -- under the same patch names, so every reader
    # downstream finds the unit and measures zero through it (ADR-129).
    off = fan.name in model.fans_off
    out = []
    for zone, master, slave, note in (
        (f"{fan.name}_supply",
         (supply, wall, "wall") if off else (supply, supply_fields, "patch"),
         (f"{fan.name}SupplyBack", wall, "wall"),
         ("is OUT OF SERVICE: a wall" if off else
          f"delivers into the plenum below it, at {model.supply_temp_c:g} degC")),
        (f"{fan.name}_return",
         (f"{fan.name}IntakeBack", wall, "wall"),
         (intake, wall, "wall") if off else (intake, intake_fields, "patch"),
         "is OUT OF SERVICE: a wall" if off else "draws from the gallery above it"),
    ):
        out.append(f"""    {zone}
    {{
        // The unit's {'bottom' if zone.endswith('supply') else 'top'} face: it {note}.
        // The other side is a wall -- the unit's own body, which is drawn and
        // not meshed, as the fan wall's depth already is (ADR-046, ADR-076).
        type        faceZone;
        zoneName    {zone};
        patches
        {{
{half('master', *master)}
{half('slave', *slave)}
        }}
    }}""")
    return out


def _fan_baffle(model: Model, fan: Panel, k: float, epsilon: float) -> str:
    supply_k = model.supply_temp_c + KELVIN
    p0 = model.pressure_pa
    # Each unit moves its share of the total, set by mass (see below).
    mass_flow = model.unit_airflow_m3h / 3600.0 * supply_density(model)
    intake, supply = f"{fan.name}Intake", f"{fan.name}Supply"

    intake_fields = f"""                patchFields
                {{
                    // A fan draws its duty whatever the gallery is doing.
                    // pressureInletOutletVelocity here let 3.9 kg/s blow back
                    // *into* the gallery against a net of 1.7 -- no fan does
                    // that -- and on every reversed face T was pinned to a
                    // guessed return temperature, inventing heat the racks
                    // never produced and leaving the energy balance open.
                    U       {{ type flowRateOutletVelocity;
                              massFlowRate {mass_flow:.6g};
                              rho rho; value uniform (0 0 0); }}
                    // A pure outlet in behaviour -- flowRateOutletVelocity
                    // admits nothing -- but written as inletOutlet because
                    // zeroGradient stores no value on the patch, and the
                    // temperature of the air crossing here is the number the
                    // energy balance is built from. The inlet value is inert;
                    // it is the supply temperature rather than a guessed
                    // return so that if anything ever did reverse, it would
                    // bring back cold air instead of inventing heat.
                    T       {{ type inletOutlet;
                              inletValue uniform {supply_k:.2f};
                              value uniform {supply_k:.2f}; }}
                    p_rgh   {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
                    p       {{ type calculated; value uniform {p0:.0f}; }}
                    k       {{ type zeroGradient; }}
                    epsilon {{ type zeroGradient; }}
                    nut     {{ type calculated; value uniform 0; }}
                    alphat  {{ type calculated; value uniform 0; }}
                }}"""

    supply_fields = f"""                patchFields
                {{
                    // {model.unit_airflow_m3h:,.0f} m3/h at {model.supply_temp_c:g} degC is
                    // {mass_flow:.4g} kg/s through {fan.area:.2f} m2,
                    // blowing into the cold aisle along the patch normal.
                    U       {{ type flowRateInletVelocity;
                              massFlowRate {mass_flow:.6g};
                              rho rho; value uniform (0 0 0); }}
                    T       {{ type fixedValue; value uniform {supply_k:.2f}; }}
                    p_rgh   {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
                    p       {{ type calculated; value uniform {p0:.0f}; }}
                    k       {{ type fixedValue; value uniform {k:.4g}; }}
                    epsilon {{ type fixedValue; value uniform {epsilon:.4g}; }}
                    nut     {{ type calculated; value uniform 0; }}
                    alphat  {{ type calculated; value uniform 0; }}
                }}"""

    # createBaffles hands the master patch to the face's owner cell, which for
    # an x-normal face of a blockMesh box is the cell at lower x. A gallery at
    # lower x than the hall (sign +1) therefore owns its units' faces and the
    # master is the intake; a gallery at the far end of the hall (sign -1) is
    # at higher x, the owner is the hall cell, and the two swap. Naming them
    # without swapping the conditions would build a unit that supplies into
    # its own return -- and it would still read as converged.
    side = "the gallery is at lower x" if fan.sign > 0 else "the gallery is at higher x"
    # A UNIT OUT OF SERVICE IS A WALL on both faces, under the same patch
    # names, so everything downstream finds it and measures zero (ADR-129).
    off = fan.name in model.fans_off
    if off:
        wall = _wall_patch_fields(k, epsilon, p0)
        intake_fields, supply_fields = wall, wall
    pairs = (
        ((intake, intake_fields), (supply, supply_fields))
        if fan.sign > 0
        else ((supply, supply_fields), (intake, intake_fields))
    )
    halves = "\n".join(
        f"""            {role}
            {{
                name    {name};
                type    {'wall' if off else 'patch'};
{fields}
            }}"""
        for role, (name, fields) in zip(("master", "slave"), pairs)
    )

    return f"""    {fan.name}
    {{
        // Where the loop is cut. Same faces, two patches: air leaves
        // the gallery through {intake} and comes back into the cold aisle
        // through {supply} at {model.supply_temp_c:g} degC. That is the fan
        // wall, without modelling a single blade.
        //
        // Both sides are set by *mass* flow. Volume would not do: the air
        // leaving is warmer and thinner than the air arriving, and in a loop
        // with nowhere to store the difference a 1% mismatch has no way out.
        //
        // master is {intake if fan.sign > 0 else supply} here because {side}.
        type        faceZone;
        zoneName    {fan.name};
        patches
        {{
{halves}
        }}
    }}"""


def decomposition(model: Model, processors: int) -> tuple[int, int, int]:
    """How to cut the box between ``processors``, as (nx, ny, nz).

    THE CUTS ARE WHAT THE RUN PAYS FOR. Every face on a processor boundary is
    a halo exchange each iteration, and slabbing one axis makes that cost grow
    with the core count while the work on each core falls. On the 1 MW hall
    (108 x 174 x 33), slabbing y costs 28.512 shared faces at 9 cores and
    53.460 at 16 -- nearly twice the communication for half the work each,
    which is why going from 9 cores to 16 bought nothing measurable. Cutting
    it 4 x 4 instead costs 27.918: the same 16 cores, 48 % less to exchange
    (ADR-113).

    A grid decomposition of `n` parts on an axis puts `n - 1` planes through
    the mesh, so the faces to exchange are the sum over the axes of
    (n - 1) x the cells in the plane normal to it. Every factorisation of the
    core count is tried -- there are never many -- and the cheapest wins. Ties
    go to the one that leaves the thickest slabs, because a subdomain one cell
    thick is a halo on both sides of nothing.

    An axis is never cut more finely than it has cells: that decomposition
    holds empty subdomains, and `decomposePar` refuses it.
    """
    cells = model.divisions
    total = cells[0] * cells[1] * cells[2]

    def faces(n: tuple[int, int, int]) -> int:
        return sum((n[a] - 1) * (total // cells[a]) for a in range(3))

    options = []
    for nx in range(1, processors + 1):
        if processors % nx or nx > cells[0]:
            continue
        for ny in range(1, processors // nx + 1):
            if (processors // nx) % ny or ny > cells[1]:
                continue
            nz = processors // (nx * ny)
            if nz > cells[2]:
                continue
            n = (nx, ny, nz)
            options.append((faces(n), -min(cells[a] // n[a] for a in range(3)), n))
    if not options:
        raise ValueError(
            f"solver.processors: {processors} cores cannot be cut out of a "
            f"{cells[0]} x {cells[1]} x {cells[2]} mesh -- every way of "
            f"splitting them leaves a subdomain with no cells in it. Use "
            f"fewer cores, or a finer mesh"
        )
    return min(options)[2]


def decompose_par_dict(model: Model, processors: int) -> str:
    """Split the box between the cores, cutting as few faces as possible.

    ``simple`` rather than scotch because the packaged build ships scotch as a
    stub, and for a box a grid is as good: every processor gets the same
    number of cells, and `decomposition` picks the grid that shares the fewest
    faces (ADR-113). Cyclic grille pairs and baffles cut by a processor
    boundary are handled by OpenFOAM's processorCyclic patches.
    """
    n = decomposition(model, processors)
    return f"""{_header(model, "dictionary", "decomposeParDict")}
numberOfSubdomains {processors};
method          simple;
coeffs
{{
    n           ({n[0]} {n[1]} {n[2]});
}}
"""


def check_fan_orientation(case_dir: str | Path, model: Model | None = None) -> list[str]:
    """Confirm createBaffles put the supply on the hall side.

    ``createBaffles`` gives the master patch the faces' original orientation
    and the slave the reverse, so which of the pair faces the data hall is
    decided by the mesh, not by this generator. For a blockMesh box with x
    increasing, the owner of an x-normal face is the cell at lower x -- which
    makes the master the gallery side and the slave the hall side. That is a
    reasonable expectation, not a guarantee, and getting it backwards builds a
    POD that blows cold air into its own return and reads as converged.

    So it is measured. The check costs one face and three points.
    """
    from aicfd.foam.polymesh import patch_normal

    pairs = fan_patches(model) if model is not None else [(FAN_INTAKE, FAN_SUPPLY)]
    fans = list(model.fans) if model is not None else [None]
    problems = []
    for (intake, supply), fan in zip(pairs, fans):
        if fan is not None and fan.name in getattr(model, "fans_off", ()):
            continue  # a wall has no direction to get wrong
        if fan is not None and fan.return_z is not None:
            # A DOWNFLOW UNIT IS THE SAME TEST TURNED ON ITS SIDE. Its two
            # faces are normal to z: the return is the top one and its cells
            # are the gallery ABOVE it, so its outward normal points down; the
            # supply is the bottom one and its cells are the plenum BELOW, so
            # its normal points up. Reversed, the unit would draw from the
            # plenum it is filling (ADR-076).
            tests = ((intake, 2, -1.0, "mechanical gallery above it"),
                     (supply, 2, +1.0, "underfloor plenum below it"))
        else:
            # The intake faces away from the hall, so its outward normal points
            # along +x for a gallery at lower x and along -x for one at the far
            # end; the supply is the other way round.
            sign = float(fan.sign) if fan is not None else 1.0
            tests = ((intake, 0, sign, "mechanical gallery"),
                     (supply, 0, -sign, "data hall"))
        for patch, axis, expected, side in tests:
            normal = patch_normal(case_dir, patch)
            if normal[axis] * expected < 0.5:
                problems.append(
                    f"{patch} should open onto the {side} (outward normal "
                    f"{'xyz'[axis]} = {expected:+.0f}) but its normal is "
                    f"({', '.join(f'{v:+.2f}' for v in normal)}). The unit's "
                    "pair is reversed: air would be supplied into the return."
                )
    return problems


# --- physics ------------------------------------------------------------------


def heat_source(rack) -> str:
    """One rack's IT load, as an absolute source on enthalpy."""
    return f"""{rack.id}Heat
{{
    type            scalarSemiImplicitSource;
    active          yes;
    scalarSemiImplicitSourceCoeffs
    {{
        selectionMode   cellZone;
        cellZone        {rack.id};
        volumeMode      absolute;
        injectionRateSuSp
        {{
            // {rack.load_kw:g} kW of IT load. The field is h because
            // thermophysicalProperties uses sensibleEnthalpy.
            h           ({rack.load_w:g} 0);
        }}
    }}
}}"""


def fv_options(model: Model) -> str:
    blocks = []
    for rack in model.racks:
        d_flow, f_flow = rack.darcy_forchheimer()
        # The rack breathes along y, so the flow axis is e2, not e1. Getting
        # this wrong builds a rack that blocks the direction it should pass.
        axes = {
            0: ("(1 0 0)", "(0 1 0)"),
            1: ("(0 1 0)", "(0 0 1)"),
            2: ("(0 0 1)", "(1 0 0)"),
        }[rack.airflow_axis]
        blocks.append(
            f"""{rack.id}Porosity
{{
    type            explicitPorositySource;
    active          yes;
    explicitPorositySourceCoeffs
    {{
        selectionMode   cellZone;
        cellZone        {rack.id};
        type            DarcyForchheimer;
        DarcyForchheimerCoeffs
        {{
            // 25 Pa at {rack.rated_airflow_m3s * 3600:,.0f} m3/h
            // ({rack.face_velocity_ms:.2f} m/s through {rack.face_area:.2f} m2),
            // resisted across the two axes the air must not take.
            d   d [0 -2 0 0 0 0 0] ({d_flow:g} {BLOCKED_D:g} {BLOCKED_D:g});
            f   f [0 -1 0 0 0 0 0] ({f_flow:.4g} {BLOCKED_F:g} {BLOCKED_F:g});
            coordinateSystem
            {{
                type        cartesian;
                origin      (0 0 0);
                coordinateRotation
                {{
                    // e1 is the flow axis: the rack's front faces the cold
                    // aisle at 90 degrees to the row.
                    type    axesRotation;
                    e1      {axes[0]};
                    e2      {axes[1]};
                }}
            }}
        }}
    }}
}}"""
        )
        # A position carrying no load gets the porous block above and no
        # source: the cabinet is there and blanked, so it resists like the
        # rest of the row and only its heat is missing. `h (0 0)` would be a
        # source injecting nothing while claiming there is IT in the cabinet
        # (ADR-054).
        if rack.load_w > 0:
            blocks.append(heat_source(rack))
    return f"""{_header(model, "dictionary", "fvOptions")}
{chr(10).join(blocks)}
"""


def turbulence_initial_values(model: Model) -> tuple[float, float]:
    """Initial k and epsilon for the whole POD.

    The velocity scale is buoyant rather than the supply face velocity, and
    epsilon is derived from k so the pair keeps a room-scale length. Flooring
    epsilon on its own collapses the turbulent viscosity to roughly molecular
    and leaves a steady solver chasing vortices a real room would damp -- see
    aicfd.case.turbulence_initial_values for the full account.
    """
    buoyant = math.sqrt(
        9.81
        * max(min(model.design_delta_t_k, 30.0), 1.0)
        / T_REFERENCE_K
        * model.domain.size[2]
    )
    characteristic = max(model.fan_face_velocity_ms, buoyant)
    k = max(1.5 * (characteristic * TURBULENCE_INTENSITY) ** 2, 1e-6)
    length_scale = LENGTH_SCALE_FRACTION * model.domain.size[2]
    return k, C_MU**0.75 * k**1.5 / length_scale


# --- control ------------------------------------------------------------------


# Partial results do not come from a functionObject. `probes` -- and every
# other functionObject, and `postProcess` -- dies in this OpenFOAM build with
#
#     error in IOstream "sha1" for operation operator<<(Ostream&, const word&)
#
# which is OSHA1stream failing inside functionObjectList's dictionary digest.
# It is a fault in the packaged library, not in any dictionary: a probes entry
# with one point and one field kills the solver at "Starting time loop" just as
# surely as a full one.
#
# So the solver writes its fields often instead, and aicfd.post samples them
# as they land (see Sampler). The measurement is identical -- the same cells at
# the same iterations -- and it costs one extra field write per sample.


def written_end(max_iterations: int, sensor_interval: int) -> int:
    """The first iteration at or past `max_iterations` that the solver WRITES.

    A steady solver writes every `writeInterval` iterations and nowhere else:
    asked for 1600 with a 500 write interval it stops at 1600 and the newest
    field on disk is 1500 -- a hundred iterations solved and thrown away, and
    every reader downstream (the coupled loop, the post, the report's "solved
    to iteration") working on a field older than the run (ADR-128).
    """
    interval = max(1, int(sensor_interval))
    return int(-(-int(max_iterations) // interval) * interval)


def control_dict(model: Model, max_iterations: int, sensor_interval: int = 100) -> str:
    return f"""{_header(model, "dictionary", "controlDict")}
application     buoyantSimpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
// An iteration cap, not a target: fvSolution's residualControl should stop the
// run first. Reaching this number means the case did not converge.
endTime         {written_end(max_iterations, sensor_interval)};
deltaT          1;
writeControl    timeStep;
// How often the run reports. Every write is a sample: the places, the mass
// balance and the energy balance all come off these fields.
writeInterval   {sensor_interval};
// Three kept, so a sampler that falls a step behind still catches up, and a
// finished run leaves the last state to look at.
purgeWrite      3;
writeFormat     ascii;
writePrecision  6;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
"""


def fv_solution(model: Model, tolerance: float) -> str:
    p0 = model.pressure_pa
    return f"""{_header(model, "dictionary", "fvSolution")}
solvers
{{
    "p_rgh.*"
    {{
        solver          GAMG;
        tolerance       1e-8;
        relTol          0.01;
        smoother        GaussSeidel;
    }}
    "(U|h|k|epsilon).*"
    {{
        solver          smoothSolver;
        smoother        GaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }}
}}

SIMPLE
{{
    momentumPredictor yes;
    nNonOrthogonalCorrectors 0;
    consistent      yes;
    // Both sides of the fan fix their mass flow, so no patch fixes p_rgh and
    // its level is undetermined. This pins it, at the site's own pressure.
    pRefCell        0;
    pRefValue       {p0:.0f};
    residualControl
    {{
        p_rgh           {tolerance:g};
        U               {tolerance:g};
        h               {tolerance:g};
        "(k|epsilon)"   {tolerance:g};
    }}
}}

relaxationFactors
{{
    fields {{ p_rgh 0.7; }}
    equations
    {{
        U               0.3;
        // The plenum and the gallery converge as a bulk mode -- the whole
        // volume warms together rather than a front sweeping through -- and
        // that mode's rate is set by this factor. Measured against 0.3 from the
        // same state: 2.5x faster to the same answer.
        h               0.7;
        "(k|epsilon)"   0.3;
    }}
}}
"""


# --- initial and boundary conditions ------------------------------------------


def warm_start(model: Model) -> str:
    """The initial temperature field, warm where the return air will be.

    A steady solve converges to the same answer from any initial condition, so
    the initial condition is free -- and starting the whole box at the supply
    temperature is the most expensive free choice available. The solver then
    has to carry heat all the way round the loop before the energy balance can
    close, and the mechanical gallery alone is a third of the domain's volume.
    Measured from a cold start: after 600 iterations the contained hot aisle
    had reached 29,9 degC but the plenum was still at 21,1 and climbing 0,6 K
    per hundred iterations, with the gallery untouched.

    So the loop is seeded with its own topology: cold upstream of the racks,
    warm everywhere the air has already passed through them -- the contained
    hot aisle, the return plenum, and the gallery. That is not an answer being
    assumed; it is the shape of the answer, and the solver is free to move
    every number in it. It is the same thing `setFields` does, and the same
    thing every commercial tool's "patch a region" or "hybrid initialisation"
    does.

    The one thing it can legitimately change is *which* steady state a
    buoyancy-driven flow settles into, if the problem admits more than one. So
    it is checked rather than trusted: ``warm_start: false`` in the spec's
    solver block converges the same case from a uniform field, and the two
    must agree (ADR-019).
    """
    nx, ny, nz = model.divisions
    cx, cy, cz = model.cell_size
    supply_k = model.supply_temp_c + KELVIN
    warm_k = supply_k + min(max(model.design_delta_t_k, 1.0), 25.0)

    blocks = model.rack_blocks
    galleries = [(g.lo[0], g.hi[0]) for g in model.galleries]

    def in_hot_aisle(y: float) -> bool:
        return any(lo <= y <= hi for lo, hi in model.hot_aisles)

    def in_gallery(x: float) -> bool:
        return any(lo <= x <= hi for lo, hi in galleries)

    def over_racks(x: float) -> bool:
        return any(lo <= x <= hi for lo, hi in blocks)

    hot_rows = [in_hot_aisle((j + 0.5) * cy) for j in range(ny)]
    values = []
    for k in range(nz):
        z = (k + 0.5) * cz
        for j in range(ny):
            for i in range(nx):
                x = (i + 0.5) * cx
                downstream = (
                    in_gallery(x)  # every gallery carries return air
                    or z > model.ceiling_z  # the plenum above the false ceiling
                    or (hot_rows[j] and over_racks(x))
                )
                values.append(warm_k if downstream else supply_k)

    body = "\n".join(f"{value:.2f}" for value in values)
    return f"""nonuniform List<scalar>
{len(values)}
(
{body}
)"""


def initial_fields(model: Model, warm: bool = True) -> dict[str, str]:
    """The 0/ directory, for the outer walls only.

    The internal patches do not exist yet -- createBaffles adds them, with the
    boundary conditions declared in createBafflesDict. Writing them here too
    would put the same choice in two files.
    """
    k, epsilon = turbulence_initial_values(model)
    supply_k = model.supply_temp_c + KELVIN
    walls = "|".join(OUTER_PATCHES)
    p0 = model.pressure_pa

    return {
        "U": f"""{_header(model, "volVectorField", "U", "0")}
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 0);

boundaryField
{{
    "({walls})" {{ type noSlip; }}
}}
""",
        "T": f"""{_header(model, "volScalarField", "T", "0")}
dimensions      [0 0 0 1 0 0 0];

// See warm_start. Seeding costs nothing and saves thousands of iterations,
// but it must be checked, not trusted: converge the same case from a uniform
// field too and confirm they land in the same place.
internalField   {warm_start(model) if warm else f"uniform {supply_k:.2f}"};

boundaryField
{{
    // Adiabatic. A POD's envelope loses little next to {model.total_load_w / 1000:.0f} kW of IT.
    "({walls})" {{ type zeroGradient; }}
}}
""",
        "p_rgh": f"""{_header(model, "volScalarField", "p_rgh", "0")}
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform {p0:.0f};

boundaryField
{{
    "({walls})" {{ type fixedFluxPressure; value uniform {p0:.0f}; }}
}}
""",
        "p": f"""{_header(model, "volScalarField", "p", "0")}
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform {p0:.0f};

boundaryField
{{
    ".*" {{ type calculated; value uniform {p0:.0f}; }}
}}
""",
        "k": f"""{_header(model, "volScalarField", "k", "0")}
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform {k:.4g};

boundaryField
{{
    "({walls})" {{ type kqRWallFunction; value uniform {k:.4g}; }}
}}
""",
        "epsilon": f"""{_header(model, "volScalarField", "epsilon", "0")}
dimensions      [0 2 -3 0 0 0 0];

internalField   uniform {epsilon:.4g};

boundaryField
{{
    "({walls})" {{ type epsilonWallFunction; value uniform {epsilon:.4g}; }}
}}
""",
        "nut": f"""{_header(model, "volScalarField", "nut", "0")}
dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    "({walls})" {{ type nutkWallFunction; value uniform 0; }}
}}
""",
        "alphat": f"""{_header(model, "volScalarField", "alphat", "0")}
dimensions      [1 -1 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    "({walls})" {{ type compressible::alphatJayatillekeWallFunction;
                  Prt 0.85; value uniform 0; }}
}}
""",
    }


# --- human-readable summary ----------------------------------------------------


def _hvac_lines(model: Model) -> list[str]:
    h = model.hvac()
    lines = []
    if h["capacity_kw"] is not None:
        lines.append(
            f"  HVAC capacity   {h['units']} x {h['unit_capacity_kw']:.1f} kW = "
            f"{h['capacity_kw']:,.0f} kW for {h['load_kw']:,.0f} kW of IT "
            f"({h['capacity_ratio'] * 100:.0f}%)"
        )
    if h["airflow_ratio"] is not None:
        lines.append(
            f"  HVAC airflow    {h['airflow_m3h']:,.0f} m3/h for {h['airflow_needed_m3h']:,.0f} "
            f"m3/h at {h['cfm_per_kw']:g} CFM/kW ({h['airflow_ratio'] * 100:.0f}%)"
        )
    return lines


def _plenum_lines(model: Model) -> list[str]:
    """What the wall between the hall and the gallery is, in the summary.

    Three arrangements, and the summary has to say which one this is: a
    single wall, a double wall with grilles in its inner leaf, or a double
    wall whose inner leaf is mesh. The last two share their geometry and
    differ in what the leaf is and in whether the building grew for it
    (ADR-058, ADR-060).
    """
    if not model.plenum_depth or not model.plenum_grilles:
        return []
    face = sum(g.area for g in model.plenum_grilles)
    if model.supply_mesh_k is not None:
        return [
            f"  Supply plenum   {model.plenum_depth:g} m deep, closed on the "
            f"hall side by 13 x 13 mm mesh over {face:.1f} m2; the hall keeps "
            f"the size it was built at",
            f"  Supply mesh     {model.plenum_face_velocity_ms:.2f} m/s "
            f"through it, {model.plenum_pressure_drop_pa or 0.0:.2f} Pa",
        ]
    return [
        f"  Supply plenum   {model.plenum_depth:g} m between the two leaves "
        f"of the hall wall, {len(model.plenum_grilles)} grille(s), "
        f"{face:.1f} m2 of face",
        f"  Supply grilles  {model.plenum_face_velocity_ms:.2f} m/s on the "
        f"face, {model.plenum_pressure_drop_pa or 0.0:.2f} Pa",
    ]


def _unit_label(model: Model) -> str:
    """What the summary calls this room's machines, pluralised where there is
    more than one: `Fan walls`, `CRACs`, `CRAHs` (ADR-102)."""
    naming = unit_naming(model.equipment, model.floor_height)
    word = naming["plural"] if model.fan_count > 1 else naming["noun"]
    return word[0].upper() + word[1:]


def summary(model: Model) -> str:
    """What the generator derived, in the user's units."""
    dx, dy, dz = model.domain.size
    k, epsilon = turbulence_initial_values(model)
    lines = [
        f"Case '{model.name}'",
        f"  Domain          {dx:g} x {dy:g} x {dz:g} m",
        f"  Mesh            {'x'.join(str(n) for n in model.divisions)} "
        f"= {model.n_cells:,} cells ("
        + " x ".join(f"{c:.2f}" for c in model.cell_size)
        + " m)",
        f"  IT load         {model.total_load_w / 1000:.1f} kW across "
        f"{len(model.racks)} rack(s)",
        # Named for what the room really has: a wall of fans, or the CRACs
        # and CRAHs that stand in it. The column stays put either way
        # (ADR-102).
        f"  {_unit_label(model):<15} "
        + (f"{model.fan_count} x " if model.fan_count > 1 else "")
        + f"{model.unit_airflow_m3h:,.0f} m3/h at "
        f"{model.supply_temp_c:.1f} degC, "
        f"{model.fan_face_velocity_ms:.2f} m/s through "
        f"{model.fans[0].area:.2f} m2" + (" each" if model.fan_count > 1 else ""),
        f"  Rack demand     {model.rack_demand_m3s * 3600:,.0f} m3/h "
        f"({model.rack_demand_m3s * 3600 / model.airflow_m3h * 100:.0f}% of supply)",
        f"  Design bulk dT  {model.design_delta_t_k:.1f} K",
        *_plenum_lines(model),
        f"  Site air        {model.altitude_m:.0f} m, {model.pressure_pa / 1000:.1f} kPa, "
        f"rho {model.rho:.3f} kg/m3",
        *_hvac_lines(model),
        f"  Turbulence      k {k:.4g} m2/s2, epsilon {epsilon:.4g} m2/s3",
        "",
        "  Internal surfaces built by createBaffles:",
    ]
    for name, panels, holes in wall_plan(model):
        holed = f", less {len(holes)} opening(s)" if holes else ""
        area = sum(p.area for p in panels)
        where = (
            f"at {panels[0].position:g} m"
            if len(panels) == 1
            else f"{len(panels)} panels"
        )
        lines.append(
            f"    {name:<22} normal {'xyz'[panels[0].axis]} {where}, "
            f"{area:.2f} m2{holed}"
        )
    # A porous surface that is not a hole in any wall has no zone in the plan
    # above, and this list is read as what createBaffles builds -- so the mesh
    # leaf, which is a surface all by itself, was built and not listed
    # (ADR-060).
    holes = {h.name for _z, _w, hs in wall_plan(model) for h in hs}
    for panel in porous(model):
        if panel.name in holes:
            continue
        lines.append(
            f"    {panel.name:<22} normal {'xyz'[panel.axis]} at "
            f"{panel.position:g} m, {panel.area:.2f} m2, "
            f"K {panel.resistance:.2f}"
        )
    for fan, (intake, supply) in zip(model.fans, fan_patches(model)):
        # A FAN WALL AND A DOWNFLOW UNIT ARE NOT THE SAME SHAPE, and this line
        # said "normal x ... y" for both. On a raised floor it printed the
        # x range of a z-normal face under the label y, so five units that
        # were correctly spread down two galleries read as three stacked in
        # one place and two in another -- a reader checking the placement was
        # shown a room that did not exist (ADR-097).
        label = fan.name + " (" + intake + "/" + supply + ")"
        (a0, a1), (b0, b1) = fan.extent
        if fan.return_z is not None:
            where = (f"horizontal, supplies at {fan.position:g} m and returns "
                     f"at {fan.return_z:g} m, x {a0:g}-{a1:g} y {b0:g}-{b1:g}")
        else:
            where = f"normal x at {fan.position:g} m, y {a0:g}-{a1:g}"
        lines.append(f"    {label:<22} {where}, {fan.area:.2f} m2")
    return "\n".join(lines) + "\n"
